### PR TITLE
Update Place Philippines

### PR DESCRIPTION
**Pull request by nvkelso**
Updating `data/856/325/09/85632509.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by nvkelso** [comment]
Resolves https://github.com/whosonfirst-data/whosonfirst-data/issues/2192 cc @youngpm.

**Comment by stepps00** [comment]
Looking at the United States country record, it looks like the `ne:id` values are integers: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-us/master/data/856/337/93/85633793.geojson

Should we update this PR to include an integer concordance value? Or should work be done in prod to switch over to string values?

**Comment by nvkelso** [comment]
I think there is logic somewhere about which concordance IDs are strings versus ints. Probably in this PR it should be an int.

**Comment by nvkelso** [comment]
Closing in favor of https://github.com/whosonfirst-data/whosonfirst-data-admin-ph/pull/27.

**Pull request closed without merging**
